### PR TITLE
Update istio documenation to use TLS Context

### PR DESCRIPTION
**Pull request by bpehling**
Add TLS Context configuration
Update tls upstream name in user-guide to be consistent with tls documentation

### CODE REVIEW

**Comment by bpehling** [comment]
#52

**Comment by richarddli** [comment]
Thanks for the PR! I assume you've tested this? :-). It looks reasonable to me.

**Comment by bpehling** [comment]
@richarddli Yes, I tested this

**Comment by richarddli** [comment]
Super, thanks!

**Pull request merged**
